name: Clawboard CI

on:
  push:
  pull_request:

jobs:
  build_and_test:
    # Avoid duplicate runs for same-repo PRs (push already validates branches).
    # Keep PR validation for forks where push events are not available in this repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.29.2

      - name: Install root deps
        run: pnpm install

      - name: Install backend deps
        run: pnpm -C backend install

      - name: Install frontend deps
        run: pnpm -C frontend install

      - name: Build frontend
        run: pnpm -C frontend build

      - name: Run backend tests
        run: pnpm -C backend test:run

      - name: Validate Docker Compose files
        run: |
          if ! command -v docker >/dev/null 2>&1; then
            echo "Docker CLI not available on this runner; skipping compose validation."
            exit 0
          fi
          if ! docker compose version >/dev/null 2>&1; then
            echo "Docker Compose plugin not available on this runner; skipping compose validation."
            exit 0
          fi
          docker compose config > /dev/null
          docker compose -f compose.yaml -f compose.traefik.yaml config > /dev/null

  deploy:
    needs: build_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH to homelab VM
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY:  ${{ secrets.SSH_KEY }}
          APP_DIR:  ${{ secrets.APP_DIR }}
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" \
            "set -e; cd '$APP_DIR'; git fetch origin main; git reset --hard origin/main; docker compose up -d --build"
